### ISSUE TITLE
Questions for SAFT-VR-Mie implementation

### ISSUE THREAD

**Issue by ianhbell** [ClapeyronThermo/Clapeyron.jl#150]
I had some questions regarding the SAFT-VR-Mie implementation, especially:

- How did you calculate the diameter d_ii? It is some magical integration method, apparently not normal Gauss-Legendre, but also, much more accurate for 5 terms than mine. I needed 15 terms in my naive Gauss-Legendre integration to get the same result as in your code, which I don't understand.
- Can you say a little bit about how you did the diagonal terms? I have been trying to map between your code and the equations in Lafitte, and there are a number of places where things are a bit different. I think that is due to optimizations in your code, but it would be nice to have that spelled out a bit more clearly.

**Comment by longemen3000** [comment]
The function that generates d_ii is here:
https://github.com/ClapeyronThermo/Clapeyron.jl/blob/360a2f6ffa45a6220f852936d55d3ecbb8875026/src/models/SAFT/SAFTVRMie/SAFTVRMie.jl#L167-L192
where 
```    u = (0.26356031971814109102031,1.41340305910651679221800,3.59642577104072208122300,7.08581000585883755692200,12.6408008442757826594300),
w = (0.5217556105828086524759,0.3986668110831759274500,7.5942449681707595390e-2,3.6117586799220484545e-3,2.3369972385776227891e-5),
```

**Comment by longemen3000** [comment]
On SAFT-VR-Mie (and other EoS) it basically comes to reduce the amount of instructions so: 
- we calculate all the parameters for component ´i´ in the outer loop
- the inner loop calculates the `j` and `i,j` parameters (that are mostly mixing rules). we do a triangular loop, so the non-diagonal contributions need to be double-counted. one thing to consider is that `a^b` operations are pretty costly, so any effort in reducing those will severely impact the implementation speed.

Also, internally, we use `a_dispchain` that fuses the calculation of the dispersion and chain terms, (there are a lot of common terms) `a_disp` and `a_chain` are also defined, because other EoS use it (mainly SAFT-gamma-Mie and variants).

Maybe the old implementation could help a bit more? it is clearer (at the cost of speed): https://github.com/ClapeyronThermo/Clapeyron.jl/tree/v0.2.3/src/models/eos/SAFT/SAFTVRMie

**Comment by longemen3000** [comment]
For the specific source of those weights, I know that the SAFT gamma Mie paper talks about a 5-point gauss-legendre, but I don't know the precise source of those weights

**Comment by ianhbell** [comment]
Indeed, I looked at the code for the calculation of d_ii, but it doesn't make sense. It isn't a normal Gauss-Legendre evaluation with weights that look like this: https://en.wikipedia.org/wiki/Gauss%E2%80%93Legendre_quadrature#Definition .  It is something quite different. And it works really well, so I would like to understand the magic that is being employed.

**Comment by ianhbell** [comment]
> On SAFT-VR-Mie (and other EoS) it basically comes to reduce the amount of instructions so:
> 
> * we calculate all the parameters for component ´i´ in the outer loop
> * the inner loop calculates the `j` and `i,j` parameters (that are mostly mixing rules). we do a triangular loop, so the non-diagonal contributions need to be double-counted. one thing to consider is that `a^b` operations are pretty costly, so any effort in reducing those will severely impact the implementation speed.
> 
> Also, internally, we use `a_dispchain` that fuses the calculation of the dispersion and chain terms, (there are a lot of common terms) `a_disp` and `a_chain` are also defined, because other EoS use it (mainly SAFT-gamma-Mie and variants).
> 
> Maybe the old implementation could help a bit more? it is clearer (at the cost of speed): https://github.com/ClapeyronThermo/Clapeyron.jl/tree/v0.2.3/src/models/eos/SAFT/SAFTVRMie

I found that also, and I was wondering how big the speedup is with these optimizations. It makes the approach more complicated, and I wonder for myself if the cost is warranted.

**Comment by longemen3000** [comment]
>  I found that also, and I was wondering how big the speedup is with these optimizations. It makes the approach more complicated, and I wonder for myself if the cost is warranted.

That version was really slow (about 100x). A lot of those slowdowns were for the association. (at first, Dictionaries were used to store the result, surprisingly AD still worked through those) Another source of slowdowns was the continuous recalculation of variables for each iteration (ρS was calculated 6 times per ij pair instead of just one, for example)

**Comment by pw0908** [comment]
Good to close this issue @ianhbell ?

**Comment by ianhbell** [comment]
Yes I think so - the last question is what diameter we *should* be implementing, but that's a different question entirely.
