### ISSUE TITLE
Improvements to solve for the association fraction

### ISSUE THREAD

**Issue by pw0908** [ClapeyronThermo/Clapeyron.jl#70]
We could consider using newer methods to solve for the association fraction:
1. https://www.tandfonline.com/doi/full/10.1080/00268976.2012.668963
2. https://pubs.acs.org/doi/10.1021/ie034041q
3. https://pubs.acs.org/doi/abs/10.1021/ie060029x
They don't look so complex and we could add them under `AssocOptions`

**Comment by longemen3000** [comment]
reading 3. we do perform that exact index reduction, but we take a step further: we fuse z[IJ] and ΔIJ (in their [IJ] notation) into one sparse matrix A[IJ]. their proposed iteration is equivalent to ours when `dampingfactor = 0.5` but we could use their initial point

**Comment by longemen3000** [comment]
One thing that is complex under our association solver was adding combining rules. a combining rule means a dense matrix of reduced indices, or at least, denser that what gains can be obtained with using an sparse matrix. Because of that, the new `combining::Symbol` keyword was added to `AssocOptions`.
- `sparse_nocombining`: the default. creates an sparse matrix.
- `sparse_nocombining`: new option. instantiates a dense matrix, but still no combining
- `elliott` Combining rule.
we use the general definition of the elliott combining rule:
```julia
Δ(i,j,a,b) = √(Δ(i,i,a,b)*Δ(j,j,a,b))
```
instead on the more EoS-specific values. (CPA and SAFT have different expressions for the mixing rules of the association energy, but they reduce to the equation above).
At the moment, if one term is associating and the other is not, we default to zero. this could be explored further in the future. 
this work was made as a byproduct of tackling #75
