### ISSUE TITLE
SMILES parser for group contribution methods

### ISSUE THREAD

**Issue by BradenDKelly** [ClapeyronThermo/Clapeyron.jl#80]
I am going to be playing with some SAFT variants, particularly group contribution methods for rather large molecules > 500 MW.

It would be real swell if there was a parser, so that given a SMILES i.d. or equivalent, all of the groups (and their amounts) were returned. `rdkit` can probably do this. I will likely look into this, but I have a feeling it will take a bit of work. I have not had to deal with using python from Julia, and don't look forward to it.

This would be a fantastic feature though. Drug molecules are such a pain.

This also reminds me that I thought there used to be an example for a (small) drug molecule for the GammaMie variant?

**Comment by pw0908** [comment]
Just to add to what Andrés said, this is indeed something we've wanted to implement for a while. We do know there are so Julia-native packages we could use to support this:
* ChemicalIdentifiers: https://github.com/longemen3000/ChemicalIdentifiers.jl
* MolecularGraphs: https://github.com/mojaie/MolecularGraph.jl
The latter supports both SMARTS and SMILES, and should hypothetically be exactly what we need for this. Andrés has already pointed out the problem with the different group types in different methodologies, however, in general, these are all fragment-based groups rather than atom-centered groups, meaning if we have a generalised enough framework, it should be compatible with all of them.

**Comment by BradenDKelly** [comment]
I have been manually entering a bunch of drug molecules, it isn't as bad as I thought it would be, but, I have discovered that gamma Mie is missing coverage. I know Sara Febra et al. added a few groups for drug molecules recently. Hopefully they do a few more. There is no coverage at all for Sulphur and that makes Saccharin very sad. Saccharin also has several sad friends :(. I also think a simple "aCH2" group would be nice, but I may be doing it wrong. it seems to be necessary for adamantane carboxylic acid.

**Comment by pw0908** [comment]
I definitely agree that the open-source database for SAFT-gamma mie  is very lacking. If youre really desperate to model your systems with SAFT-gamma Mie, I would suggest gPROMS (commercial software) which supports over 100 groups. Annoyingly, the developer of these groups is a former member of the Imperial group which made SAFT-gamma Mie so it's annoying this wasn't published...

Aside from that, if you are willing to wait, we are developing a parameter estimation framework which would allow you to fit these missing groups yourself?

Also, aCH2 can't exist since a refers to aromatic (I don't think an aromatic ring can have a CH2 group?). If youre looking for the CH2 groups on the adamantane cage, that would be cCH2 (c for cyclic). I would warn you about the validity of using a group fitted for a ring to model a cage...

**Comment by pw0908** [comment]
On the topic of SMILES parsers, I just remembered that Simon Mueller has a code (in python) that does exactly what we need: https://github.com/simonmb/fragmentation_algorithm

Perhaps combining this method with MolecularGraph.jl might be enough to develop a complete SMILES parser?

**Comment by BradenDKelly** [comment]
THere is also https://www.researchgate.net/publication/321657289_JRgui_A_Python_Program_of_Joback_and_Reid_Method which is a parser for the Joback method. I was thinking of highjacking it at some point and stripping out the GUI part

**Comment by longemen3000** [comment]
I was looking at the algorithm that Pierre posted, and all the calls on rdkit had MolecularGraph counterparts, so I'm gonna start porting that algorithm in another repository. On a parallel road, the latest Rdkit (with windows support, because I happen to have a windows machine) was added recently to Yggdrasil, (thanks @giordano for the BinaryBuilder recipe!)

**Comment by funkvps** [comment]
> I definitely agree that the open-source database for SAFT-gamma mie is very lacking. If youre really desperate to model your systems with SAFT-gamma Mie, I would suggest gPROMS (commercial software) which supports over 100 groups. Annoyingly, the developer of these groups is a former member of the Imperial group which made SAFT-gamma Mie so it's annoying this wasn't published...
> 
> Aside from that, if you are willing to wait, we are developing a parameter estimation framework which would allow you to fit these missing groups yourself?
> 
> Also, aCH2 can't exist since a refers to aromatic (I don't think an aromatic ring can have a CH2 group?). If youre looking for the CH2 groups on the adamantane cage, that would be cCH2 (c for cyclic). I would warn you about the validity of using a group fitted for a ring to model a cage...

If it's OK, please refer to attach for the group and component in commercial software.
It's very different with this publication. anyway. 

https://pubs.acs.org/doi/10.1021/acs.jced.0c00746?fig=fig1&ref=pdf

[data.zip](https://github.com/ClapeyronThermo/Clapeyron.jl/files/10985866/data.zip)

**Comment by pw0908** [comment]
Is this database from gPROMS?

> If it's OK, please refer to attach for the group and component in commercial software.

**Comment by funkvps** [comment]
> Is this database from gPROMS?
> 
> > If it's OK, please refer to attach for the group and component in commercial software.

correct. An very old version of gproms

**Comment by longemen3000** [comment]
this functionality is available in https://github.com/ClapeyronThermo/GCIdentifier.jl (not registered yet)

**Comment by pw0908** [comment]
GCIdentifier is now registered!
